### ISSUE TITLE
Numbers on grid are predetermined instead of being randomized 

### ISSUE THREAD

**Issue by sunilt4** [ABusyProgrammer/PrinOfSoft-FinalProject#1]
[ 1,2,3,4,5,6,7,8,9,
 4,5,6,7,8,9,1,2,3,
 7,8,9,1,2,3,4,5,6,
 3,1,2,6,4,5,9,7,8,
 5,6,4,9,7,8,3,1,2,
 9,7,8,3,1,2,6,4,5,
 2,3,1,5,6,4,8,9,7,
 6,4,5,8,9,7,2,3,1,
 8,9,7,2,3,1,5,6,4]

**Comment by ABusyProgrammer** [comment]
This way, the puzzle will have a higher degree of randomness, which will improve the overall game experience.
