### ISSUE TITLE
Dividing the Puzzle-Board into Sub-Puzzles

### ISSUE THREAD

**Issue by ABusyProgrammer** [ABusyProgrammer/PrinOfSoft-FinalProject#2]
The current board is 9 * 9, with no borders to separate the quadrants. For styling purposes, it would be better to have a sub-border that will divide the entire puzzle board into 9 sub-quadrants.

More specifically, to satisfy this issue:L
- [ ] Board has major border that splits puzzle into 9 quadrants, 3 per row and 3 per column

**Comment by MandoCuesta** [comment]
When participating as a typical user of this game, I had encountered an interesting problem.
This is issue involved being able to manipulate the numbers already generated. As a player in my head I said "what is this?". As a programmer I said "The value is not fixed". As a member of the company I said "This is a big problem".  The fix to this would be to make the value fix/remove the drop down list from it.

- [ ] The Drop Down has somehow been removed from the "should be fixed" values.

**Comment by ABusyProgrammer** [comment]
An unrequired extra. Not needed
