### ISSUE TITLE
Every Cell/Quadrant is editable 

### ISSUE THREAD

**Issue by sunilt4** [ABusyProgrammer/PrinOfSoft-FinalProject#3]
The user when they open the game can change the numbers of each cell as the predetermined cells generated by the Math.random() function is editable by the drop down list.

**Comment by ABusyProgrammer** [comment]
To declare this issue as fixed, the puzzle should not allow the user to edit those cells that have numbers filled in during the puzzle generation process. The user has to play the game and solve the puzzle with the given set of filled cells

**Comment by ABusyProgrammer** [comment]
It can work even without this improvement
